version: "3.9"

services:
  client:
    build: ./client
    container_name: client
    env_file:
      - ./client/.env
    restart: always

  server:
    build: ./server
    container_name: server
    env_file:
      - ./server/.env
    restart: always

  nginx:
    image: nginx:stable
    container_name: nginx
    depends_on:
      - client
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
